export const queryKeys = {
    sessions: ['sessions'] as const,
    kanban: ['kanban'] as const,
    modelsCatalog: ['models-catalog'] as const,
    workspaces: ['workspaces'] as const,
    workspace: (workspaceId: string) => ['workspace', workspaceId] as const,
    workspaceWorkItems: (workspaceId: string) => ['workspace-work-items', workspaceId] as const,
    workspaceKanban: (workspaceId: string) => ['workspace-kanban', workspaceId] as const,
    workspaceJobs: (workspaceId: string) => ['workspace-jobs', workspaceId] as const,
    workspaceJobLog: (workspaceId: string, jobId: string) => ['workspace-job-log', workspaceId, jobId] as const,
    githubRepos: ['github-repos'] as const,
    githubWorkItems: ['github-work-items'] as const,
    githubKanban: ['github-kanban'] as const,
    githubJobs: ['github-jobs'] as const,
    githubWorkItemDetail: (workItemKey: string) => ['github-work-item-detail', workItemKey] as const,
    githubJobLog: (jobId: string) => ['github-job-log', jobId] as const,
    session: (sessionId: string) => ['session', sessionId] as const,
    messages: (sessionId: string) => ['messages', sessionId] as const,
    machines: ['machines'] as const,
    gitStatus: (sessionId: string) => ['git-status', sessionId] as const,
    sessionFiles: (sessionId: string, query: string) => ['session-files', sessionId, query] as const,
    sessionDirectory: (sessionId: string, path: string) => ['session-directory', sessionId, path] as const,
    sessionFile: (sessionId: string, path: string) => ['session-file', sessionId, path] as const,
    gitFileDiff: (sessionId: string, path: string, staged?: boolean) => [
        'git-file-diff',
        sessionId,
        path,
        staged ? 'staged' : 'unstaged'
    ] as const,
    slashCommands: (sessionId: string) => ['slash-commands', sessionId] as const,
    skills: (sessionId: string) => ['skills', sessionId] as const,
}
